# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ADMMsggm <- function(S, group_idx, penalty, diag_ind, diag_grp, diag_include, lambda, alpha, gamma, rho, tau_incr, tau_decr, nu, tol_abs, tol_rel, maxiter) {
    .Call(`_grasps_ADMMsggm`, S, group_idx, penalty, diag_ind, diag_grp, diag_include, lambda, alpha, gamma, rho, tau_incr, tau_decr, nu, tol_abs, tol_rel, maxiter)
}

ADMMsggm_CV <- function(X, group_idx, penalty, diag_ind, diag_grp, diag_include, lambdas, alphas, gamma, rho, tau_incr, tau_decr, nu, tol_abs, tol_rel, maxiter, kfold) {
    .Call(`_grasps_ADMMsggm_CV`, X, group_idx, penalty, diag_ind, diag_grp, diag_include, lambdas, alphas, gamma, rho, tau_incr, tau_decr, nu, tol_abs, tol_rel, maxiter, kfold)
}

ADMMsggm_IC <- function(S, group_idx, penalty, diag_ind, diag_grp, diag_include, lambdas, alphas, gamma, rho, tau_incr, tau_decr, nu, tol_abs, tol_rel, maxiter, crit, n, ebic_tuning) {
    .Call(`_grasps_ADMMsggm_IC`, S, group_idx, penalty, diag_ind, diag_grp, diag_include, lambdas, alphas, gamma, rho, tau_incr, tau_decr, nu, tol_abs, tol_rel, maxiter, crit, n, ebic_tuning)
}

soft_matrix <- function(M, Thres) {
    .Call(`_grasps_soft_matrix`, M, Thres)
}

